spring.application.name=hms-api

spring.datasource.url=jdbc:postgresql://localhost:5433/hms
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.out-of-order=true
spring.jooq.sql-dialect=postgres

server.port=8082
hms.auth.url=http://localhost:8081
hms.web.url=http://localhost:5173

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081
springdoc.swagger-ui.oauth.client-id=hms-api
springdoc.swagger-ui.oauth.client-secret=
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true